export enum OauthError {
  UNAUTHORIZED = 'unauthorized',
  FORBIDDEN = 'forbidden',
  INVALID_CLIENT = 'invalid_client',
  USER_NOT_FOUND = 'user_not_found',
  GENERATE_TOKEN_ERROR = 'generate_token_error',
  AUTHORIZATION_CODE_INVALID = 'authorization_code_invalid',
  INCORRECT_CREDENTIALS = 'incorrect_credentials',
  CLIENT_UNAVAILABLE = 'client_unavailable',
  INVALID_REDIRECT_URI = 'invalid_redirect_uri',
  REFRESH_TOKEN_EXPIRED = 'refresh_token_expired',
  REVOKE_TOKEN_FAILED = 'revoke_token_failed',
  OUT_OF_SCOPE = 'out_of_scope',
  REFRESH_TOKEN_UNSUPPORTED = 'refresh_token_unsupported',
  INVALID_PHONE = 'invalid_phone',
  INVALID_OTP = 'invalid_otp',
  REQUEST_OTP_LIMIT = 'request_otp_limit',
  EXCEED_OTP_LIMIT = 'exceed_otp_limit',
  EXCEED_VERIFY_OTP_LIMIT = 'exceed_verify_otp_limit',
}
