import { BaseIcon } from '../icon/BaseIcon';

export const baseIconConfig = {
  iconCheck: () => <BaseIcon check />,
  iconClose: () => <BaseIcon close />,
  iconClear: () => <BaseIcon closeCircle />,
  iconSelect: () => <BaseIcon expandUpDown />,
  iconSpinner: () => <BaseIcon spinner />,
  iconLoader: () => <BaseIcon loader />,
  iconRadioChecked: () => <BaseIcon radioChecked />,
  iconRadioUnchecked: () => <BaseIcon radioUnchecked />,
  iconCheckboxChecked: () => <BaseIcon checkboxChecked />,
  iconCheckboxUnchecked: () => <BaseIcon checkboxUnchecked />,
  iconPrev: () => <BaseIcon chevronLeft />,
  iconNext: () => <BaseIcon chevronRight />,
  iconDate: () => <BaseIcon calendar />,
  iconRemove: () => <BaseIcon closeCircle />,
  iconRequired: () => <BaseIcon required />,
  iconTooltip: () => <BaseIcon info />,
  iconSearch: () => <BaseIcon search />,
  iconSort: () => <BaseIcon sort />,
  iconOrder: () => <BaseIcon order />,
  iconOrderUp: () => <BaseIcon orderUp />,
  iconOrderDown: () => <BaseIcon orderDown />,
  iconCopy: () => <BaseIcon copy />,
  iconDots: () => <BaseIcon dots />,
  iconX: () => <BaseIcon x />,
  iconDetails: () => <BaseIcon details />,
  iconDragIndicator: () => <BaseIcon dragIndicator />,

  iconArrowUp: () => <BaseIcon arrowUp />,
  iconArrowDown: () => <BaseIcon arrowDown />,
  iconArrowLeft: () => <BaseIcon arrowLeft />,
  iconArrowRight: () => <BaseIcon arrowRight />,
  iconChevronUp: () => <BaseIcon chevronUp />,
  iconChevronDown: () => <BaseIcon chevronDown />,
  iconChevronLeft: () => <BaseIcon chevronLeft />,
  iconChevronRight: () => <BaseIcon chevronRight />,

  iconInfo: () => <BaseIcon info />,
  iconSuccess: () => <BaseIcon success />,
  iconWarning: () => <BaseIcon warning />,
  iconDanger: () => <BaseIcon danger />,
  iconQuestion: () => <BaseIcon question />,
  iconError: () => <BaseIcon error />,

  iconEmpty: () => <BaseIcon empty />,
  iconEyeOn: () => <BaseIcon eye />,
  iconEyeOff: () => <BaseIcon eyeOff />,
  iconEnabled: () => <BaseIcon enabled />,
  iconDisabled: () => <BaseIcon disabled />,

  iconCreate: () => <BaseIcon create />,
  iconUpdate: () => <BaseIcon update />,
  iconDelete: () => <BaseIcon delete />,
  iconRefresh: () => <BaseIcon refresh />,

  iconUpload: () => <BaseIcon upload />,
  iconImage: () => <BaseIcon image />,
  iconImageUpload: () => <BaseIcon imageUpload />,
  iconVideo: () => <BaseIcon video />,
  iconVideoUpload: () => <BaseIcon videoUpload />,
  iconFile: () => <BaseIcon file />,
  iconFileUpload: () => <BaseIcon fileUpload />,
  iconAudio: () => <BaseIcon audio />,
  iconAudioUpload: () => <BaseIcon audioUpload />,
  iconLinkAdd: () => <BaseIcon linkAdd />,
  iconVideoPlay: () => <BaseIcon videoPlay />,
  iconVideoPaused: () => <BaseIcon videoPaused />,
};
