// oxlint-disable no-duplicate-enum-values
/* eslint @typescript-eslint/no-duplicate-enum-values: 0 */
export enum BaseIconVariant {
  //System
  loader = 'svg-spinners:3-dots-fade',
  spinner = 'svg-spinners:180-ring',
  //Operation
  create = 'tabler:plus',
  update = 'tabler:edit',
  delete = 'tabler:trash',
  check = 'tabler:check',
  close = 'tabler:x',
  closeCircle = 'tabler:circle-x-filled',
  refresh = 'tabler:refresh',
  search = 'tabler:search',
  sort = 'tabler:arrows-sort',
  order = 'tabler:caret-up-down-filled',
  orderUp = 'tabler:square-rounded-arrow-up-filled',
  orderDown = 'tabler:square-rounded-arrow-down-filled',
  changePassword = 'tabler:password-user',
  copy = 'tabler:copy',
  dots = 'tabler:dots',
  dotsVertical = 'tabler:dots-vertical',
  x = 'tabler:x',
  list = 'tabler:list',
  details = 'tabler:list-search',
  dragIndicator = 'material-symbols:drag-indicator',
  //Media
  upload = 'tabler:upload',
  image = 'tabler:photo',
  imageUpload = 'tabler:photo-up',
  video = 'tabler:video',
  videoUpload = 'tabler:video-plus',
  file = 'tabler:file',
  fileUpload = 'tabler:file-upload',
  audio = 'tabler:file-music',
  audioUpload = 'tabler:music-up',
  linkAdd = 'tabler:link-plus',
  linkExternal = 'tabler:external-link',
  videoPlay = 'tabler:player-play-filled',
  videoPaused = 'tabler:player-pause-filled',
  //Semantic
  info = 'tabler:info-circle-filled',
  success = 'tabler:circle-check-filled',
  warning = 'tabler:alert-hexagon-filled',
  danger = 'tabler:alert-triangle-filled',
  error = 'tabler:circle-x-filled',
  question = 'tabler:help-square-rounded-filled',
  //Direcrion
  arrowUp = 'tabler:arrow-up',
  arrowDown = 'tabler:arrow-down',
  arrowLeft = 'tabler:arrow-left',
  arrowRight = 'tabler:arrow-right',
  chevronUp = 'tabler:chevron-up',
  chevronDown = 'tabler:chevron-down',
  chevronLeft = 'tabler:chevron-left',
  chevronRight = 'tabler:chevron-right',
  expandUpDown = 'tabler:selector',
  //control
  checkboxUnchecked = 'tabler:square',
  checkboxChecked = 'tabler:square-check-filled',
  radioUnchecked = 'tabler:circle',
  radioChecked = 'tabler:circle-dot-filled',
  //object
  address = 'tabler:map-2',
  idCard = 'tabler:id',
  group = 'tabler:users-group',
  user = 'tabler:user',
  map = 'tabler:map',
  calendar = 'tabler:calendar',
  crown = 'fluent:crown-24-filled',
  description = 'tabler:file-description',
  qr = 'tabler:qrcode',
  location = 'tabler:current-location-filled',
  //state
  eye = 'tabler:eye',
  eyeOff = 'tabler:eye-off',
  empty = 'tabler:device-tablet-search',
  required = 'clarity:asterisk-solid',
  enabled = 'tabler:circle-check-filled',
  disabled = 'tabler:forbid-filled',
  // action
  login = 'tabler:login-2',
  logout = 'tabler:logout',
  scan = 'tabler:scan',
}
