/* eslint @typescript-eslint/no-duplicate-enum-values: 0 */
// src/shared/components/icons/iconVariants.ts

export enum IconVariant {
  variant = 'placeholder',
  keyFilled = 'tabler:key-filled',
  admin = 'tabler:user-cog',
  client = 'tabler:server-2',
  vendor = 'tabler:building-store',
  config = 'tabler:adjustments-cog',
  bankAccount = 'tabler:credit-card',
  bank = 'tabler:building-bank',
  unconnected = 'tabler:plug',
  connected = 'tabler:plug-connected',
  appWindow = 'tabler:app-window',
  buildingSkyscraper = 'tabler:building-skyscraper',
  user = 'tabler:user',
  growth = 'tabler:growth',
  seeding = 'tabler:seedling',
  liveView = 'tabler:live-view',
  map = 'tabler:map',
  stackFront = 'tabler:stack-front',
  folderOpen = 'tabler:folder-open',
  alignBoxLeftTop = 'tabler:align-box-left-top',
  adjustmentsHorizontal = 'tabler:adjustments-horizontal',
  lot = 'tabler:brand-minecraft',
  template = 'tabler:template',
  tablerLoader3 = 'tabler:loader-3',
  qr = 'tabler:qrcode',
  connect = 'tabler:cloud-data-connection',
  userPlus = 'tabler:user-plus',
  usersGroup = 'tabler:users-group',
  vectorBezier2 = 'tabler:vector-bezier-2',
  notebook = 'tabler:notebook',
  brand4chan = 'tabler:brand-4chan',
  bug = 'tabler:bug',
  frustum = 'tabler:frustum',
  cylinder = 'tabler:cylinder',
  databaseLeak = 'tabler:database-leak',
  microscope = 'tabler:microscope',
  tree = 'tabler:tree',

  // ── Factory module (mới) ──────────────────────────────────────────────────
  factory = 'tabler:building-factory-2',
  warehouse = 'tabler:building-warehouse',
  packageImport = 'tabler:package-import',
  packageExport = 'tabler:package-export',
  transfer = 'tabler:transfer',
  delivery ='tabler:truck-delivery',
  processFlow = 'tabler:circuit-diode',
  chartBar = 'tabler:chart-bar',
  chartLine = 'tabler:chart-line',
}

// https://icon-sets.iconify.design